# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            WhatsAndroid
tagline:          'Hello, Android!'
description:      'Android'
url:              https://erehmi.github.io/
baseurl:          /

author:
  name:           'erehmi'
  url:            http://weibo.com/erehmi

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/erehmi/
